### ISSUE TITLE
XRP Robot WiFi not working when the password is shorter than 8 characters or has escape character '\'

### ISSUE THREAD

**Issue by REVSIX** [wpilibsuite/xrp-wpilib-firmware#33]
When configuring the password for an XRP robot in the json, we found that our computer was unable to connect to the XRP robot when the configured password contained capital letters or spaces. There was no documentation saying not to, so we assumed it would work.

**Comment by jpokornyiii** [comment]
I'll check the upper case letters but there are several limitations it seems (see this: https://www.reddit.com/r/DeeperNetwork/comments/t7ggt2/comment/i0vezbe/). Also #32 notes that the password can't be less than 8 characters due to WPA standards. I will add checks to prevent this in the future. For now, please do not use spaces or special characters such as & in your password.

**Comment by jpokornyiii** [comment]
I tried: XRP WPILIB and it worked for me. Can you try again and see if that works? From testing, the only known illegal characters are \ and " due to the way javascript interprets them. Additionally, because of WPA2 standards, the password needs to be between 8 and 63 characters long.

**Comment by REVSIX** [comment]
> I tried: XRP WPILIB and it worked for me. Can you try again and see if that works? From testing, the only known illegal characters are \ and " due to the way javascript interprets them. Additionally, because of WPA2 standards, the password needs to be between 8 and 63 characters long.


Oh! Understood! I'm guessing the issue was too few characters then, but having checks implemented to make sure you don't get locked out of connecting to your xrp would be super helpful! Thank you!

**Comment by jpokornyiii** [comment]
I confirmed "X -1&#!$+%@.*|()<>{}^_?=[];:'`~/" works. All of these special characters should be available for use.
